#!/bin/bash
# run through the 4 conditions

python3 train_initial.py > training_progress.txt & disown
python3 train_NF1.py > training_progress.txt & disown
python3 train_CF1.py > training_progress.txt & disown
python3 train_NF2.py > training_progress.txt & disown
python3 train_CF2.py > training_progress.txt & disown
